name: Docker

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: package docker
      run: |
        VERSION=$(date +%s)
        docker login docker.pkg.github.com --username ethomsondemo --password ${{ secrets.GITHUB_TOKEN }}
        docker build . --file Dockerfile --tag docker.pkg.github.com/ethomsondemo/helloworld/app:${VERSION}
        docker push docker.pkg.github.com/ethomsondemo/helloworld/app:${VERSION}
      env:
        CI: true
